# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/extractor_sierra

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/extractor_sierra

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/extractor_sierra/CMakeFiles /workspaces/extractor_sierra//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/extractor_sierra/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named robot_extractor

# Build rule for target.
robot_extractor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 robot_extractor
.PHONY : robot_extractor

# fast build rule for target.
robot_extractor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/robot_extractor.dir/build.make CMakeFiles/robot_extractor.dir/build
.PHONY : robot_extractor/fast

#=============================================================================
# Target rules for targets named export_robot_mkv

# Build rule for target.
export_robot_mkv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 export_robot_mkv
.PHONY : export_robot_mkv

# fast build rule for target.
export_robot_mkv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/export_robot_mkv.dir/build.make CMakeFiles/export_robot_mkv.dir/build
.PHONY : export_robot_mkv/fast

src/core/rbt_parser.o: src/core/rbt_parser.cpp.o
.PHONY : src/core/rbt_parser.o

# target to build an object file
src/core/rbt_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/robot_extractor.dir/build.make CMakeFiles/robot_extractor.dir/src/core/rbt_parser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/export_robot_mkv.dir/build.make CMakeFiles/export_robot_mkv.dir/src/core/rbt_parser.cpp.o
.PHONY : src/core/rbt_parser.cpp.o

src/core/rbt_parser.i: src/core/rbt_parser.cpp.i
.PHONY : src/core/rbt_parser.i

# target to preprocess a source file
src/core/rbt_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/robot_extractor.dir/build.make CMakeFiles/robot_extractor.dir/src/core/rbt_parser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/export_robot_mkv.dir/build.make CMakeFiles/export_robot_mkv.dir/src/core/rbt_parser.cpp.i
.PHONY : src/core/rbt_parser.cpp.i

src/core/rbt_parser.s: src/core/rbt_parser.cpp.s
.PHONY : src/core/rbt_parser.s

# target to generate assembly for a file
src/core/rbt_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/robot_extractor.dir/build.make CMakeFiles/robot_extractor.dir/src/core/rbt_parser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/export_robot_mkv.dir/build.make CMakeFiles/export_robot_mkv.dir/src/core/rbt_parser.cpp.s
.PHONY : src/core/rbt_parser.cpp.s

src/export_robot_mkv.o: src/export_robot_mkv.cpp.o
.PHONY : src/export_robot_mkv.o

# target to build an object file
src/export_robot_mkv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/export_robot_mkv.dir/build.make CMakeFiles/export_robot_mkv.dir/src/export_robot_mkv.cpp.o
.PHONY : src/export_robot_mkv.cpp.o

src/export_robot_mkv.i: src/export_robot_mkv.cpp.i
.PHONY : src/export_robot_mkv.i

# target to preprocess a source file
src/export_robot_mkv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/export_robot_mkv.dir/build.make CMakeFiles/export_robot_mkv.dir/src/export_robot_mkv.cpp.i
.PHONY : src/export_robot_mkv.cpp.i

src/export_robot_mkv.s: src/export_robot_mkv.cpp.s
.PHONY : src/export_robot_mkv.s

# target to generate assembly for a file
src/export_robot_mkv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/export_robot_mkv.dir/build.make CMakeFiles/export_robot_mkv.dir/src/export_robot_mkv.cpp.s
.PHONY : src/export_robot_mkv.cpp.s

src/formats/decompressor_lzs.o: src/formats/decompressor_lzs.cpp.o
.PHONY : src/formats/decompressor_lzs.o

# target to build an object file
src/formats/decompressor_lzs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/robot_extractor.dir/build.make CMakeFiles/robot_extractor.dir/src/formats/decompressor_lzs.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/export_robot_mkv.dir/build.make CMakeFiles/export_robot_mkv.dir/src/formats/decompressor_lzs.cpp.o
.PHONY : src/formats/decompressor_lzs.cpp.o

src/formats/decompressor_lzs.i: src/formats/decompressor_lzs.cpp.i
.PHONY : src/formats/decompressor_lzs.i

# target to preprocess a source file
src/formats/decompressor_lzs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/robot_extractor.dir/build.make CMakeFiles/robot_extractor.dir/src/formats/decompressor_lzs.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/export_robot_mkv.dir/build.make CMakeFiles/export_robot_mkv.dir/src/formats/decompressor_lzs.cpp.i
.PHONY : src/formats/decompressor_lzs.cpp.i

src/formats/decompressor_lzs.s: src/formats/decompressor_lzs.cpp.s
.PHONY : src/formats/decompressor_lzs.s

# target to generate assembly for a file
src/formats/decompressor_lzs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/robot_extractor.dir/build.make CMakeFiles/robot_extractor.dir/src/formats/decompressor_lzs.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/export_robot_mkv.dir/build.make CMakeFiles/export_robot_mkv.dir/src/formats/decompressor_lzs.cpp.s
.PHONY : src/formats/decompressor_lzs.cpp.s

src/formats/dpcm.o: src/formats/dpcm.cpp.o
.PHONY : src/formats/dpcm.o

# target to build an object file
src/formats/dpcm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/robot_extractor.dir/build.make CMakeFiles/robot_extractor.dir/src/formats/dpcm.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/export_robot_mkv.dir/build.make CMakeFiles/export_robot_mkv.dir/src/formats/dpcm.cpp.o
.PHONY : src/formats/dpcm.cpp.o

src/formats/dpcm.i: src/formats/dpcm.cpp.i
.PHONY : src/formats/dpcm.i

# target to preprocess a source file
src/formats/dpcm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/robot_extractor.dir/build.make CMakeFiles/robot_extractor.dir/src/formats/dpcm.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/export_robot_mkv.dir/build.make CMakeFiles/export_robot_mkv.dir/src/formats/dpcm.cpp.i
.PHONY : src/formats/dpcm.cpp.i

src/formats/dpcm.s: src/formats/dpcm.cpp.s
.PHONY : src/formats/dpcm.s

# target to generate assembly for a file
src/formats/dpcm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/robot_extractor.dir/build.make CMakeFiles/robot_extractor.dir/src/formats/dpcm.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/export_robot_mkv.dir/build.make CMakeFiles/export_robot_mkv.dir/src/formats/dpcm.cpp.s
.PHONY : src/formats/dpcm.cpp.s

src/formats/lzs.o: src/formats/lzs.cpp.o
.PHONY : src/formats/lzs.o

# target to build an object file
src/formats/lzs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/robot_extractor.dir/build.make CMakeFiles/robot_extractor.dir/src/formats/lzs.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/export_robot_mkv.dir/build.make CMakeFiles/export_robot_mkv.dir/src/formats/lzs.cpp.o
.PHONY : src/formats/lzs.cpp.o

src/formats/lzs.i: src/formats/lzs.cpp.i
.PHONY : src/formats/lzs.i

# target to preprocess a source file
src/formats/lzs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/robot_extractor.dir/build.make CMakeFiles/robot_extractor.dir/src/formats/lzs.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/export_robot_mkv.dir/build.make CMakeFiles/export_robot_mkv.dir/src/formats/lzs.cpp.i
.PHONY : src/formats/lzs.cpp.i

src/formats/lzs.s: src/formats/lzs.cpp.s
.PHONY : src/formats/lzs.s

# target to generate assembly for a file
src/formats/lzs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/robot_extractor.dir/build.make CMakeFiles/robot_extractor.dir/src/formats/lzs.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/export_robot_mkv.dir/build.make CMakeFiles/export_robot_mkv.dir/src/formats/lzs.cpp.s
.PHONY : src/formats/lzs.cpp.s

src/formats/robot_mkv_exporter.o: src/formats/robot_mkv_exporter.cpp.o
.PHONY : src/formats/robot_mkv_exporter.o

# target to build an object file
src/formats/robot_mkv_exporter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/export_robot_mkv.dir/build.make CMakeFiles/export_robot_mkv.dir/src/formats/robot_mkv_exporter.cpp.o
.PHONY : src/formats/robot_mkv_exporter.cpp.o

src/formats/robot_mkv_exporter.i: src/formats/robot_mkv_exporter.cpp.i
.PHONY : src/formats/robot_mkv_exporter.i

# target to preprocess a source file
src/formats/robot_mkv_exporter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/export_robot_mkv.dir/build.make CMakeFiles/export_robot_mkv.dir/src/formats/robot_mkv_exporter.cpp.i
.PHONY : src/formats/robot_mkv_exporter.cpp.i

src/formats/robot_mkv_exporter.s: src/formats/robot_mkv_exporter.cpp.s
.PHONY : src/formats/robot_mkv_exporter.s

# target to generate assembly for a file
src/formats/robot_mkv_exporter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/export_robot_mkv.dir/build.make CMakeFiles/export_robot_mkv.dir/src/formats/robot_mkv_exporter.cpp.s
.PHONY : src/formats/robot_mkv_exporter.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/robot_extractor.dir/build.make CMakeFiles/robot_extractor.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/robot_extractor.dir/build.make CMakeFiles/robot_extractor.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/robot_extractor.dir/build.make CMakeFiles/robot_extractor.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils/sci_util.o: src/utils/sci_util.cpp.o
.PHONY : src/utils/sci_util.o

# target to build an object file
src/utils/sci_util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/robot_extractor.dir/build.make CMakeFiles/robot_extractor.dir/src/utils/sci_util.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/export_robot_mkv.dir/build.make CMakeFiles/export_robot_mkv.dir/src/utils/sci_util.cpp.o
.PHONY : src/utils/sci_util.cpp.o

src/utils/sci_util.i: src/utils/sci_util.cpp.i
.PHONY : src/utils/sci_util.i

# target to preprocess a source file
src/utils/sci_util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/robot_extractor.dir/build.make CMakeFiles/robot_extractor.dir/src/utils/sci_util.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/export_robot_mkv.dir/build.make CMakeFiles/export_robot_mkv.dir/src/utils/sci_util.cpp.i
.PHONY : src/utils/sci_util.cpp.i

src/utils/sci_util.s: src/utils/sci_util.cpp.s
.PHONY : src/utils/sci_util.s

# target to generate assembly for a file
src/utils/sci_util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/robot_extractor.dir/build.make CMakeFiles/robot_extractor.dir/src/utils/sci_util.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/export_robot_mkv.dir/build.make CMakeFiles/export_robot_mkv.dir/src/utils/sci_util.cpp.s
.PHONY : src/utils/sci_util.cpp.s

src/utils/stb_impl.o: src/utils/stb_impl.cpp.o
.PHONY : src/utils/stb_impl.o

# target to build an object file
src/utils/stb_impl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/export_robot_mkv.dir/build.make CMakeFiles/export_robot_mkv.dir/src/utils/stb_impl.cpp.o
.PHONY : src/utils/stb_impl.cpp.o

src/utils/stb_impl.i: src/utils/stb_impl.cpp.i
.PHONY : src/utils/stb_impl.i

# target to preprocess a source file
src/utils/stb_impl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/export_robot_mkv.dir/build.make CMakeFiles/export_robot_mkv.dir/src/utils/stb_impl.cpp.i
.PHONY : src/utils/stb_impl.cpp.i

src/utils/stb_impl.s: src/utils/stb_impl.cpp.s
.PHONY : src/utils/stb_impl.s

# target to generate assembly for a file
src/utils/stb_impl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/export_robot_mkv.dir/build.make CMakeFiles/export_robot_mkv.dir/src/utils/stb_impl.cpp.s
.PHONY : src/utils/stb_impl.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... export_robot_mkv"
	@echo "... robot_extractor"
	@echo "... src/core/rbt_parser.o"
	@echo "... src/core/rbt_parser.i"
	@echo "... src/core/rbt_parser.s"
	@echo "... src/export_robot_mkv.o"
	@echo "... src/export_robot_mkv.i"
	@echo "... src/export_robot_mkv.s"
	@echo "... src/formats/decompressor_lzs.o"
	@echo "... src/formats/decompressor_lzs.i"
	@echo "... src/formats/decompressor_lzs.s"
	@echo "... src/formats/dpcm.o"
	@echo "... src/formats/dpcm.i"
	@echo "... src/formats/dpcm.s"
	@echo "... src/formats/lzs.o"
	@echo "... src/formats/lzs.i"
	@echo "... src/formats/lzs.s"
	@echo "... src/formats/robot_mkv_exporter.o"
	@echo "... src/formats/robot_mkv_exporter.i"
	@echo "... src/formats/robot_mkv_exporter.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils/sci_util.o"
	@echo "... src/utils/sci_util.i"
	@echo "... src/utils/sci_util.s"
	@echo "... src/utils/stb_impl.o"
	@echo "... src/utils/stb_impl.i"
	@echo "... src/utils/stb_impl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

